"""
Generates LinkedIn posts from digest content using Claude API.
Strips private info, extracts themes, generates post in Robert's style.
"""
import json
import logging
import random
import os
import httpx
from config import ANTHROPIC_API_KEY

IMGFLIP_USERNAME = os.getenv("IMGFLIP_USERNAME", "")
IMGFLIP_PASSWORD = os.getenv("IMGFLIP_PASSWORD", "")

logger = logging.getLogger(__name__)

FORMATS = [
    "FORMAT 1: Case Study — 'I built X — here's what it does and why it matters'",
    "FORMAT 2: Before vs Now — 'This used to take hours. Now it takes seconds.'",
    "FORMAT 3: Hot Take — 'Unpopular opinion about AI/media/business'",
    "FORMAT 4: Scannable List — '5 things I learned building X'",
    "FORMAT 5: Question Post — short case + genuine question for comments",
    "FORMAT 6: Meta/Transparent — 'This post was written by AI and I just approved it. Here's why that matters.'",
]

SYSTEM_PROMPT = """You are a LinkedIn ghostwriter for Robert — here's who he is and what he's built:

=== WHO ROBERT IS ===
- Entrepreneur and media operator based in Tashkent, Uzbekistan (relocated from Russia in March 2022)
- Co-founder of ZBS Media — independent media holding (~15 people, bootstrapped, no VC)
- Produces news, podcasts, rap digests, sports content, commercial video
- Building a children's animation project about cultures of Uzbekistan (Plan Banan)
- Runs an ecological project — 14 shoreline cleanups per year at Charvak reservoir
- Works with international clients on AI automation (Guatemala, Uzbekistan)
- Runs a recruiting platform (TrabajaYa)
- Helps his father's tech company (Indivision) with AI integration
- Recently traveled to China
- Not a developer by training — a media operator who learned to build with AI
- Speaks Russian natively, posts on LinkedIn in English

=== WHAT ROBERT HAS ACTUALLY BUILT (use these as case studies) ===
1. Telegram News Bot — scans 40 news channels, auto-generates posts in Uzbek language via Claude API, posts to a 25K+ subscriber channel. No human editor needed.
2. Daily Morning Digest — bot collects messages from 30+ work chats overnight, Claude summarizes everything into a structured briefing sent at 8am. Replaced 45 min of catching up.
3. Revenue Opportunity Scanner — scans 29 work chats, found 300+ business opportunities, ranks them by priority. Weekly auto-scan + Tinder-style swipe review.
4. CRM Bot in Telegram — full team scheduling, project tracking, finance module, blogger directory, automated reminders. The whole team uses it instead of spreadsheets.
5. LinkedIn Auto-Poster — reads daily digests, Claude generates posts in Robert's style, sends for approval in Telegram, publishes with meme attached. THIS is how this post might have been created.
6. Claude Personal Assistant Bot — Telegram bot with vision, voice (Whisper), web search, tool use. A personal AI that understands context.
7. Children's Animation Pipeline — AI-assisted script writing, content planning for 25+ episodes about Uzbek cultures.
8. SaveCharvak Ecology Project — coordinating 14 cleanup events per year with sponsors, managing logistics through bots.

=== THE SELLING ANGLE (this is strategic) ===
Robert's LinkedIn is not a diary. It's a sales channel for AI automation services.
Every post should make readers think: "Wait, one person built all this? I need this for my business."
The goal: attract clients who want AI automation for their operations.
Target audience: founders, COOs, agency owners, media companies, SMBs who feel overwhelmed.

=== POST FORMATS (rotate between these) ===

FORMAT 1: Case Study — "I built X, here's what it does"
- Start with the problem (manual, slow, expensive)
- Show what you built (specific, concrete)
- Share the result (time saved, process eliminated, scale achieved)
- End with: "If you're doing X manually, there's a better way."
- This is the MONEY format. Use it most often.

FORMAT 2: Before vs Now
- "6 months ago I spent 45 minutes every morning reading through 30 Telegram chats. Now a bot does it in 10 seconds and sends me a structured briefing."
- Show the transformation with specific details

FORMAT 3: Hot Take
- "You don't need to be a developer to build AI tools. I'm a media operator who never wrote code before 2024."
- Back it up with your story

FORMAT 4: Scannable List
- "5 things I automated this year and how much time each saves"
- Each item is a concrete tool/system with a real result

FORMAT 5: Question Post
- Share one case study briefly, then ask: "What's the one process in your business you wish you could automate?"

FORMAT 6: Meta/Transparent
- Be honest that this post was generated by AI and approved by you in Telegram
- Explain WHY that's the point — you built the system, the AI executes, you curate
- This format is powerful because it demonstrates the product while discussing it

=== WRITING STYLE ===
- Language: ENGLISH only
- Tone: Casual, direct, real. Like texting a smart friend about work.
- Length: 100–300 words
- Uses "—" em dashes
- Concrete over abstract. Numbers over adjectives. Results over philosophy.
- References real tools: Telegram, Claude API, Whisper, Railway, Python
- Name the tools you use — Claude, not "AI assistant". Telegram, not "messaging platform".
- OK to mention ZBS Media, Plan Banan, SaveCharvak, TrabajaYa by name — these are public brands
- OK to say "my team of 15" or "bootstrapped" — this is positioning, not private data

=== PRIVACY RULES — still NEVER include: ===
- Specific revenue, budgets, or financial figures ($X amounts)
- Client names unless explicitly public (Karakoram, Indivision — ask first)
- Team member names
- Exact follower/subscriber counts (say "growing channel" not "25K subscribers")
- Internal financial details or salary info

=== OUTPUT ===
Pick the format that fits the topic best. Default to FORMAT 1 (Case Study) if unsure — it converts best.
Write ONLY the post text. No labels, no meta-commentary.

CRITICAL FORMATTING: LinkedIn does NOT support markdown. NEVER use:
- Asterisks for bold (**text** or *text*)
- Underscores for italic
- Hash symbols for headers (#)
- Backticks for code
Plain text only. Use line breaks and emoji for structure."""

MEME_PROMPT = """Based on this LinkedIn post, suggest exactly ONE meme concept for supermeme.ai.

Return ONLY a JSON object:
{
  "search_query": "2-4 word meme template name for supermeme.ai",
  "top_text": "short top text",
  "bottom_text": "short bottom text",
  "description": "one sentence why this meme fits"
}

Return ONLY valid JSON, no markdown, no backticks, no explanation."""


def clean_post_text(text: str) -> str:
    """Strip any markdown formatting that LinkedIn doesn't support."""
    import re
    # Remove bold **text** or __text__
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'__(.+?)__', r'\1', text)
    # Remove italic *text* or _text_
    text = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'\1', text)
    # Remove headers
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    # Remove backticks
    text = text.replace('`', '')
    return text.strip()


async def generate_post_from_digest(digest_text: str) -> dict:
    """Generate a LinkedIn post from digest content."""
    async with httpx.AsyncClient(timeout=60) as client:
        # Generate post
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 1000,
                "system": SYSTEM_PROMPT,
                "messages": [
                    {
                        "role": "user",
                        "content": (
                            f"Use this format: {random.choice(FORMATS)}\n\n"
                            f"Here is my current context — daily digests, open work items, and life situation. "
                            f"Extract something interesting and write a LinkedIn post. "
                            f"Pick a theme that connects to broader trends (AI, media, entrepreneurship, productivity). "
                            f"Remember: NEVER reveal private details, names, numbers, or clients.\n\n"
                            f"{digest_text}"
                        )
                    }
                ],
            },
        )
        resp.raise_for_status()
        data = resp.json()
        post_text = clean_post_text(data["content"][0]["text"])

        # Generate meme suggestion
        meme = await generate_meme_suggestion(client, post_text)

        return {"post_text": post_text, "meme": meme}


async def generate_post_from_topic(topic: str) -> dict:
    """Generate a LinkedIn post from a manual topic/thought."""
    async with httpx.AsyncClient(timeout=60) as client:
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 1000,
                "system": SYSTEM_PROMPT,
                "messages": [
                    {
                        "role": "user",
                        "content": f"Use this format: {random.choice(FORMATS)}\n\nWrite a LinkedIn post based on this thought:\n\n{topic}"
                    }
                ],
            },
        )
        resp.raise_for_status()
        data = resp.json()
        post_text = clean_post_text(data["content"][0]["text"])

        meme = await generate_meme_suggestion(client, post_text)

        return {"post_text": post_text, "meme": meme}


async def generate_meme_suggestion(client: httpx.AsyncClient, post_text: str) -> dict:
    """Generate a meme using free Imgflip API."""

    # Popular meme templates with IDs
    MEME_TEMPLATES = {
        "Drake Hotline Bling": "181913649",
        "Distracted Boyfriend": "112126428",
        "Two Buttons": "87743020",
        "Change My Mind": "129242436",
        "Expanding Brain": "93895088",
        "Is This A Pigeon": "100777631",
        "Waiting Skeleton": "4087833",
        "Running Away Balloon": "131087935",
        "Left Exit 12 Off Ramp": "124822590",
        "Buff Doge vs Cheems": "247375501",
        "Disaster Girl": "97984",
        "Clown Applying Makeup": "252600902",
        "Always Has Been": "252758727",
        "Trade Offer": "309868304",
        "Anakin Padme 4 Panel": "322841258",
        "This Is Fine": "55311130",
        "Tuxedo Winnie The Pooh": "222403160",
        "Sad Pablo Escobar": "174908189",
        "Think About It": "148715956",
        "One Does Not Simply": "61579",
        "Batman Slapping Robin": "438680",
        "Roll Safe Think About It": "89370399",
        "Gru's Plan": "131940431",
        "Train hitting bus": "247113703",
    }

    template_list = "\n".join([f"- {name}" for name in MEME_TEMPLATES.keys()])

    # Step 1: Ask Claude to pick template + write text
    try:
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 300,
                "messages": [
                    {
                        "role": "user",
                        "content": (
                            f"Based on this LinkedIn post, create a meme.\n\n"
                            f"Available templates:\n{template_list}\n\n"
                            f"Return ONLY a JSON object:\n"
                            f'{{"template": "exact template name from list", "text0": "top text (short)", "text1": "bottom text (short)"}}\n\n'
                            f"Pick the most fitting template. Keep texts under 8 words each. Be funny.\n"
                            f"Return ONLY valid JSON, no markdown.\n\n"
                            f"Post:\n{post_text}"
                        ),
                    }
                ],
            },
        )
        resp.raise_for_status()
        raw = resp.json()["content"][0]["text"].strip()
        cleaned = raw.replace("```json", "").replace("```", "").strip()
        meme_data = json.loads(cleaned)
    except Exception as e:
        logger.error(f"Claude meme pick error: {e}")
        return {"source": "fallback", "description": "Could not generate meme"}

    template_name = meme_data.get("template", "Drake Hotline Bling")
    template_id = MEME_TEMPLATES.get(template_name, "181913649")
    text0 = meme_data.get("text0", "")
    text1 = meme_data.get("text1", "")

    # Step 2: Generate meme image via Imgflip API (free)
    if IMGFLIP_USERNAME and IMGFLIP_PASSWORD:
        try:
            meme_resp = await client.post(
                "https://api.imgflip.com/caption_image",
                data={
                    "template_id": template_id,
                    "username": IMGFLIP_USERNAME,
                    "password": IMGFLIP_PASSWORD,
                    "text0": text0,
                    "text1": text1,
                },
                timeout=15,
            )
            result = meme_resp.json()

            if result.get("success"):
                image_url = result["data"]["url"]
                return {
                    "source": "imgflip",
                    "template": template_name,
                    "text0": text0,
                    "text1": text1,
                    "image_url": image_url,
                }
            else:
                logger.error(f"Imgflip error: {result.get('error_message')}")
        except Exception as e:
            logger.error(f"Imgflip API error: {e}")

    # Fallback: return text-only suggestion
    return {
        "source": "claude_suggestion",
        "template": template_name,
        "text0": text0,
        "text1": text1,
        "description": f"Use '{template_name}' meme template",
    }
